name: medicalapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bard_api: ^1.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.18.1

  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  date_format: ^2.0.7

  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
